2018-02-26T08:39:57.938Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error executing chaincode: transaction returned with failure: [composerchannel-d00a5331]Calling chaincode Invoke() returned error response [Error: Object with ID 'Participant:org.peckstadt.cargo' in collection with ID '$sysregistries' does not exist]. Sending ERROR message back to peer
    at /home/vagrant/hyperledger/server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T08:39:57.942Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: error executing chaincode: transaction returned with failure: [composerchannel-d00a5331]Calling chaincode Invoke() returned error response [Error: Object with ID 'Participant:org.peckstadt.cargo' in collection with ID '$sysregistries' does not exist]. Sending ERROR message back to peer","stack":"Error: Error trying to query business network. Error: error executing chaincode: transaction returned with failure: [composerchannel-d00a5331]Calling chaincode Invoke() returned error response [Error: Object with ID 'Participant:org.peckstadt.cargo' in collection with ID '$sysregistries' does not exist]. Sending ERROR message back to peer\n    at channel.queryByChaincode.then.catch (/home/vagrant/hyperledger/server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:820:34)\n    at <anonymous>"}$
