2018-03-27T15:51:24.119Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error executing chaincode: transaction returned with failure: [composerchannel-89f5a2ae]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID '0' in collection with ID 'Asset:org.gov.fundtracker.MMDA' as the object already exists]. Sending ERROR message back to peer
    at /home/vagrant/hyperledger/server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-03-27T15:51:24.121Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: error executing chaincode: transaction returned with failure: [composerchannel-89f5a2ae]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID '0' in collection with ID 'Asset:org.gov.fundtracker.MMDA' as the object already exists]. Sending ERROR message back to peer\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: error executing chaincode: transaction returned with failure: [composerchannel-89f5a2ae]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID '0' in collection with ID 'Asset:org.gov.fundtracker.MMDA' as the object already exists]. Sending ERROR message back to peer\n\n    at _initializeChannel.then.then.then.then.catch (/home/vagrant/hyperledger/server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:927:34)\n    at <anonymous>"}$
