2018-04-10T12:29:40.286Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: Peer has rejected transaction '4eabab9c592893fa96807acfd79a479d7a4f03c28ca814537ffc8e5d65f0dcd4' with code MVCC_READ_CONFLICT","stack":"Error: Error trying invoke business network. Error: Peer has rejected transaction '4eabab9c592893fa96807acfd79a479d7a4f03c28ca814537ffc8e5d65f0dcd4' with code MVCC_READ_CONFLICT\n    at _initializeChannel.then.then.then.then.catch (/home/vagrant/hyperledger/server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:927:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-04-10T12:29:43.785Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: error executing chaincode: transaction returned with failure: [composerchannel-39cc61ca]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID '2' in collection with ID 'Asset:org.gov.fundtracker.Project' as the object already exists]. Sending ERROR message back to peer
    at /home/vagrant/hyperledger/server/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-04-10T12:29:43.789Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: error executing chaincode: transaction returned with failure: [composerchannel-39cc61ca]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID '2' in collection with ID 'Asset:org.gov.fundtracker.Project' as the object already exists]. Sending ERROR message back to peer\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: error executing chaincode: transaction returned with failure: [composerchannel-39cc61ca]Calling chaincode Invoke() returned error response [Error: Failed to add object with ID '2' in collection with ID 'Asset:org.gov.fundtracker.Project' as the object already exists]. Sending ERROR message back to peer\n\n    at _initializeChannel.then.then.then.then.catch (/home/vagrant/hyperledger/server/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:927:34)\n    at <anonymous>"}$
